# Operations on Arrays

---

More than linear algebra this focuses on performing the operations using numpy.

In [2]:
import numpy as np

In [3]:
small = np.array([2,3,4])

## Multiplication

In [4]:
print(small * 3)

[ 6  9 12]


Multiplying two arrays of the same size multiplies each of the elements by the corresponding element in the same location of the second list.

In [5]:
large = np.array([20,30,40])

In [6]:
print(small * large)

[ 40  90 160]


In [8]:
large_2D = np.array([[20,30,40],
                     [80,90,100]])

In [9]:
print(small * large_2D)

[[ 40  90 160]
 [160 270 400]]
